version: '3.8'

services:
  server:
    platform: linux/x86_64
    build:
      context: .
    ports:
      - "4567:4567"

  test:
    platform: linux/x86_64
    build:
      context: .
    command: ["bundle", "exec", "rspec"]
